### ISSUE TITLE
Particle system do not seem to take window scaling in consideration

### ISSUE THREAD

**Issue by jfbilodeau** [korlibs/korge-next#343]
Thank you so much for creating world-base coordinate particle. I've notice that the particle scale incorrectly if the window size is different than the game resolutions. For example:

```kotlin
class GameModule : Module() {
    val game = Game()
    override val size = SizeInt(game.stageWidth, game.stageHeight)
    override val windowSize = SizeInt(game.stageWidth * 2, game.stageHeight * 2)  // Doubling window size
```

**Comment by soywiz** [comment]
I believe this shouldn't be an issue already with the latest change so I'm closing it. Feel free to reopen if it is not the case 👍

**Comment by jfbilodeau** [comment]
Not trying to reopen the issue, but I can't test on my machine. When I try to build Korge, I get the following error:
`e: /home/jfbilodeau/Projects/korge-next/korte/src/jvmAndroidMain/kotlin/com/soywiz/korte/internal/KorteLock.kt: (3, 23): Actual class 'KorteLock' has no corresponding expected declaration`

Any ideas?

**Comment by soywiz** [comment]
CI is compiling `master` fine.

Can you try to?:
* `gradlew clean`
* `gradlew --stop`
* `gradlew publishToMavenLocal`

And see if it helps?

**Comment by jfbilodeau** [comment]
Thanks. I should have tried that first, but coffee was still in the mug and not in the bloodstream.

I was able to compile but I noticed a number of oddities.

for starters, in `ParticleEmitterRead.kt`, I noticed you are setting `emitter.textureName = null` before loading the texture, therefore forcing it to use the default texture. Removing the line loads the texture for me.

I also noticed that the particles are not clipped to the viewport. See the screenshot for reference.

Also, `localCoord = false` does not align with the parent sprite, and moved when the window is resized. If you'd like, I can provide a build demonstrating those behaviours.
![image](https://user-images.githubusercontent.com/5893654/135754018-b0aaaa86-a7c4-48f1-93bb-6b4d1a2fc5b2.png)

**Comment by jfbilodeau** [comment]
![image](https://user-images.githubusercontent.com/5893654/135754079-59a20f8d-4206-4080-9e1d-47057cd60b85.png)

**Comment by jfbilodeau** [comment]
Hey @soywiz, I hate to be a pain, but #364 does not seem to have fixed the problem for me. Particles are not clipped to the viewing area. For example, in the following image, there should be solid black bars in the stretched window. Instead, I see particles (the coloured clouds). I suspect that it's due to FastSprite not clipping.

![image](https://user-images.githubusercontent.com/5893654/142777858-6fee9d6b-2801-4f02-a8f6-dc6e140d6abe.png)

**Comment by soywiz** [comment]
Hey @jfbilodeau right now I'm on holidays/break from personal projects, so I won't be responsive and I won't be able to fix this soon myself. But I will check it out after I return if nobody has fixed it by then.

And BTW really cool screenshot!

**Comment by jfbilodeau** [comment]
> 

No problems. Have a great holiday!

**Comment by soywiz** [comment]
I'm back. @jfbilodeau what's the status of this issue? It was fixed? Something remaining?

**Comment by jfbilodeau** [comment]
Hey @soywiz! Hope you have a great vacation. Sorry, I haven't worked on the issue, but testing this morning with korge-next and the issue is still there for me.
![image](https://user-images.githubusercontent.com/5893654/148939549-ac3af052-a717-4997-a6b2-670528859782.png)
